# Generated by Django 4.0.1 on 2022-01-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='primermodelo',
            table='segundo_modelo',
        ),
    ]
