# Generated by Django 4.0.1 on 2022-01-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0002_segundomodelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primermodelo',
            name='campo_uno',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='primermodelo',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
