# Generated by Django 4.0.1 on 2022-01-21 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0005_segundomodelo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='primermodelo',
            table='Primer_modelo',
        ),
    ]
