# Generated by Django 4.0.1 on 2022-01-21 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerComponente', '0007_alter_primermodelo_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrimerModelo',
        ),
    ]
